services:
  postgres:
    image: postgres:17.4-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metrics -d metrics" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "P@ssw0rd"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "${DB_PORT_EXTERNAL:-5432}:5432"
    restart: always

volumes:
  pgdata:
