// Code generated by MockGen. DO NOT EDIT.
// Source: batchupdater.go
//
// Generated by this command:
//
//	mockgen -source=batchupdater.go -destination=mocks/mock_batchupdater.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/korobkovandrey/runtime-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockbatchUpdaterRepository is a mock of batchUpdaterRepository interface.
type MockbatchUpdaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbatchUpdaterRepositoryMockRecorder
	isgomock struct{}
}

// MockbatchUpdaterRepositoryMockRecorder is the mock recorder for MockbatchUpdaterRepository.
type MockbatchUpdaterRepositoryMockRecorder struct {
	mock *MockbatchUpdaterRepository
}

// NewMockbatchUpdaterRepository creates a new mock instance.
func NewMockbatchUpdaterRepository(ctrl *gomock.Controller) *MockbatchUpdaterRepository {
	mock := &MockbatchUpdaterRepository{ctrl: ctrl}
	mock.recorder = &MockbatchUpdaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbatchUpdaterRepository) EXPECT() *MockbatchUpdaterRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdateBatch mocks base method.
func (m *MockbatchUpdaterRepository) CreateOrUpdateBatch(ctx context.Context, mrs []*model.MetricRequest) ([]*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateBatch", ctx, mrs)
	ret0, _ := ret[0].([]*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateBatch indicates an expected call of CreateOrUpdateBatch.
func (mr *MockbatchUpdaterRepositoryMockRecorder) CreateOrUpdateBatch(ctx, mrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateBatch", reflect.TypeOf((*MockbatchUpdaterRepository)(nil).CreateOrUpdateBatch), ctx, mrs)
}

// FindBatch mocks base method.
func (m *MockbatchUpdaterRepository) FindBatch(ctx context.Context, mrs []*model.MetricRequest) ([]*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBatch", ctx, mrs)
	ret0, _ := ret[0].([]*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBatch indicates an expected call of FindBatch.
func (mr *MockbatchUpdaterRepositoryMockRecorder) FindBatch(ctx, mrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBatch", reflect.TypeOf((*MockbatchUpdaterRepository)(nil).FindBatch), ctx, mrs)
}
