// Code generated by MockGen. DO NOT EDIT.
// Source: updater.go
//
// Generated by this command:
//
//	mockgen -source=updater.go -destination=mocks/mock_updater.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/korobkovandrey/runtime-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockupdaterRepository is a mock of updaterRepository interface.
type MockupdaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockupdaterRepositoryMockRecorder
	isgomock struct{}
}

// MockupdaterRepositoryMockRecorder is the mock recorder for MockupdaterRepository.
type MockupdaterRepositoryMockRecorder struct {
	mock *MockupdaterRepository
}

// NewMockupdaterRepository creates a new mock instance.
func NewMockupdaterRepository(ctrl *gomock.Controller) *MockupdaterRepository {
	mock := &MockupdaterRepository{ctrl: ctrl}
	mock.recorder = &MockupdaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdaterRepository) EXPECT() *MockupdaterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockupdaterRepository) Create(arg0 context.Context, arg1 *model.MetricRequest) (*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockupdaterRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockupdaterRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockupdaterRepository) Find(arg0 context.Context, arg1 *model.MetricRequest) (*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockupdaterRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockupdaterRepository)(nil).Find), arg0, arg1)
}

// Update mocks base method.
func (m *MockupdaterRepository) Update(arg0 context.Context, arg1 *model.MetricRequest) (*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockupdaterRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockupdaterRepository)(nil).Update), arg0, arg1)
}
