// Code generated by MockGen. DO NOT EDIT.
// Source: index.go
//
// Generated by this command:
//
//	mockgen -source=index.go -destination=mocks/mock_allfinder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/korobkovandrey/runtime-metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAllFinder is a mock of AllFinder interface.
type MockAllFinder struct {
	isgomock struct{}
	ctrl     *gomock.Controller
	recorder *MockAllFinderMockRecorder
}

// MockAllFinderMockRecorder is the mock recorder for MockAllFinder.
type MockAllFinderMockRecorder struct {
	mock *MockAllFinder
}

// NewMockAllFinder creates a new mock instance.
func NewMockAllFinder(ctrl *gomock.Controller) *MockAllFinder {
	mock := &MockAllFinder{ctrl: ctrl}
	mock.recorder = &MockAllFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllFinder) EXPECT() *MockAllFinderMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockAllFinder) FindAll(arg0 context.Context) ([]*model.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*model.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAllFinderMockRecorder) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAllFinder)(nil).FindAll), arg0)
}
