// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_UNKNOWN MetricType = 0
	MetricType_GAUGE   MetricType = 1
	MetricType_COUNTER MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "UNKNOWN",
		1: "GAUGE",
		2: "COUNTER",
	}
	MetricType_value = map[string]int32{
		"UNKNOWN": 0,
		"GAUGE":   1,
		"COUNTER": 2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_proto_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	Value         float64    `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Delta         int64      `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	Type          MetricType `protobuf:"varint,2,opt,name=type,proto3,enum=runtime_metrics.MetricType" json:"type,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_UNKNOWN
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_api_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proto_metrics_proto_rawDescGZIP(), []int{2}
}

var File_api_proto_metrics_proto protoreflect.FileDescriptor

const file_api_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/metrics.proto\x12\x0fruntime_metrics\"u\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.runtime_metrics.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x03R\x05delta\"<\n" +
	"\aMetrics\x121\n" +
	"\ametrics\x18\x01 \x03(\v2\x17.runtime_metrics.MetricR\ametrics\"\n" +
	"\n" +
	"\bResponse*1\n" +
	"\n" +
	"MetricType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01\x12\v\n" +
	"\aCOUNTER\x10\x022\x8e\x01\n" +
	"\x0eMetricsService\x12<\n" +
	"\x06Update\x12\x17.runtime_metrics.Metric\x1a\x19.runtime_metrics.Response\x12>\n" +
	"\aUpdates\x12\x18.runtime_metrics.Metrics\x1a\x19.runtime_metrics.ResponseB5Z3github.com/korobkovandrey/runtime-metrics/pkg/protob\x06proto3"

var (
	file_api_proto_metrics_proto_rawDescOnce sync.Once
	file_api_proto_metrics_proto_rawDescData []byte
)

func file_api_proto_metrics_proto_rawDescGZIP() []byte {
	file_api_proto_metrics_proto_rawDescOnce.Do(func() {
		file_api_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_metrics_proto_rawDesc), len(file_api_proto_metrics_proto_rawDesc)))
	})
	return file_api_proto_metrics_proto_rawDescData
}

var file_api_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_metrics_proto_goTypes = []any{
	(MetricType)(0),  // 0: runtime_metrics.MetricType
	(*Metric)(nil),   // 1: runtime_metrics.Metric
	(*Metrics)(nil),  // 2: runtime_metrics.Metrics
	(*Response)(nil), // 3: runtime_metrics.Response
}
var file_api_proto_metrics_proto_depIdxs = []int32{
	0, // 0: runtime_metrics.Metric.type:type_name -> runtime_metrics.MetricType
	1, // 1: runtime_metrics.Metrics.metrics:type_name -> runtime_metrics.Metric
	1, // 2: runtime_metrics.MetricsService.Update:input_type -> runtime_metrics.Metric
	2, // 3: runtime_metrics.MetricsService.Updates:input_type -> runtime_metrics.Metrics
	3, // 4: runtime_metrics.MetricsService.Update:output_type -> runtime_metrics.Response
	3, // 5: runtime_metrics.MetricsService.Updates:output_type -> runtime_metrics.Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_metrics_proto_init() }
func file_api_proto_metrics_proto_init() {
	if File_api_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_metrics_proto_rawDesc), len(file_api_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_metrics_proto_goTypes,
		DependencyIndexes: file_api_proto_metrics_proto_depIdxs,
		EnumInfos:         file_api_proto_metrics_proto_enumTypes,
		MessageInfos:      file_api_proto_metrics_proto_msgTypes,
	}.Build()
	File_api_proto_metrics_proto = out.File
	file_api_proto_metrics_proto_goTypes = nil
	file_api_proto_metrics_proto_depIdxs = nil
}
